CREATE TABLE 'users' ('id' INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 'username' TEXT NOT NULL, 'pass' TEXT NOT NULL);

CREATE TABLE 'userpriv' ('id' INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 'uid' INTEGER NOT NULL, 'rng' INTEGER NOT NULL, 'sec' TEXT NOT NULL);
