<?php
$cobot->loadModule("m_test.php");
$cobot->loadModule("m_google.php");
$cobot->loadModule("m_nickserv.php");
$cobot->loadModule("m_joinpart.php");
$cobot->loadModule("m_quit.php");
$cobot->loadModule("m_nick.php");
$cobot->loadModule("m_weather.php");
$cobot->loadModule("m_hash.php");
$cobot->loadModule("m_youtube.php");
